export enum appConfig {
    name = 'Gym Craft',
    baseUrlDEV = 'http://localhost:5173',
    baseAppUrlDEV = 'http://localhost:5173/app',
    baseUrlPROD = 'https://gymcraft.damianwroblewski.com',
    baseAppUrlPROD = 'https://gymcraft.damianwroblewski.com/app',
    openAIapiUrl = 'https://api.openai.com/v1/chat/completions',
    proxyApiUrlDEV = 'http://localhost:3000/api/generate-plan',
    proxyApiUrlPROD = 'https://gym-craft-ai-proxy.onrender.com/api/generate-plan',
    weeklyReportApiUrlDEV = 'http://localhost:3000/api/weekly-report',
    weeklyReportApiUrlPROD = 'https://gym-craft-ai-proxy.onrender.com/api/weekly-report',
    explainRunApiUrlDEV = 'http://localhost:3000/api/explain-run',
    explainRunApiUrlPROD = 'https://gym-craft-ai-proxy.onrender.com/api/explain-run',
    internalGarminApiUrlDEV = 'http://localhost:5000',
    internalGarminApiUrlPROD = 'https://gymcraft-curl-cffi.onrender.com',
    plansApiUrl = '/api/plans',
    generalPlanLimitApiUrl = '/api/general-plan-limit',
    administratorEmail = 'dwroblewski89@gmail.com',
    model = 'gpt-4o-mini',
    openAIcompletionSeed = 1,
    openAIcompletionTemperature = 0.2,
    planLimit = 10,
}

export const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
