export const formDataMock = {
    personalInfo: {
        sex: 'female',
        age: 30,
        height: 166,
        weight: 52,
        medicalConditions: 'No',
    },
    goals: {
        mainGoals: {
            'general-fitness-and-health': false,
            'lose-weight': true,
            'gain-muscle': false,
            'body-definition': true,
            'athletic-performance': false,
            'stress-reduction': false,
            other: false,
        },
        otherGoalsDescription: '',
    },
    experience: {
        activityLevel: '2-5-years',
        activityHistory: 'just gym',
        enjoyedExercises: 'I like running',
        dislikedExercises: "I can't do deadlifts",
    },
    lifestyle: {
        job: 'sedentary',
        hourCapacity: '7-10h',
        trainingDays: {
            monday: false,
            tuesday: true,
            wednesday: true,
            thursday: true,
            friday: false,
            saturday: true,
            sunday: true,
        },
    },
    fitnessLevel: {
        fitnessLevel: 6,
        currentActivities: 'Go to a gym and run twice a week',
        physicalLimitations: 'no',
    },
    equipment: {
        freeWeights: true,
        trainingMachines: true,
        treadmill: true,
        rowingMachine: true,
        stationaryBike: true,
        elliptical: true,
        stairMaster: true,
        resistanceBands: true,
        trx: true,
        calisthenics: true,
        mtbBike: false,
        roadBike: false,
    },
};
